builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    dir: cmd/podgen
    ldflags: "-s -w -X main.version={{.Tag}}"

archives:
  - name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    replacements:
      386: i386
      amd64: x86_64
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md